# Generated by Django 5.0.6 on 2024-07-10 01:39

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='periodo_escolar',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), api.models.max_value_current_year]),
        ),
    ]
