# Generated by Django 5.0.6 on 2024-07-10 09:26

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clase_periodo_escolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parciales',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='parcial',
        ),
        migrations.AddField(
            model_name='notas',
            name='c_parcial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='final_primer_semestre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='final_segundo_semestre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='p_parcial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='periodo_escolar',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), api.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='notas',
            name='s_parcial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='t_parcial',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
        migrations.DeleteModel(
            name='Parciales',
        ),
    ]
