# Generated by Django 5.0.6 on 2024-07-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_parciales_semestre_remove_notas_parcial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='c_parcial',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='final_primer_semestre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='final_segundo_semestre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota_final',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='s_parcial',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='t_parcial',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
