# Generated by Django 5.0.6 on 2024-07-17 02:15

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notas_c_parcial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='guardian_apellidos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='guardian_nombres',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='periodo_escolar',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), api.models.max_value_current_year]),
        ),
        migrations.DeleteModel(
            name='Matriculas',
        ),
    ]
